"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QualityKind = exports.CiceroKind = exports.OrthoKind = exports.CheckState = exports.CheckProfile = exports.UserPermission = exports.createApi = exports.Litera5Api = void 0;
var Litera5Api_1 = require("./Litera5Api");
Object.defineProperty(exports, "Litera5Api", { enumerable: true, get: function () { return Litera5Api_1.Litera5Api; } });
Object.defineProperty(exports, "createApi", { enumerable: true, get: function () { return Litera5Api_1.createApi; } });
var enums_1 = require("./enums");
Object.defineProperty(exports, "UserPermission", { enumerable: true, get: function () { return enums_1.UserPermission; } });
Object.defineProperty(exports, "CheckProfile", { enumerable: true, get: function () { return enums_1.CheckProfile; } });
Object.defineProperty(exports, "CheckState", { enumerable: true, get: function () { return enums_1.CheckState; } });
Object.defineProperty(exports, "OrthoKind", { enumerable: true, get: function () { return enums_1.OrthoKind; } });
Object.defineProperty(exports, "CiceroKind", { enumerable: true, get: function () { return enums_1.CiceroKind; } });
Object.defineProperty(exports, "QualityKind", { enumerable: true, get: function () { return enums_1.QualityKind; } });
